// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet6_ModelisezEtcreezUneBaseDeDonnee.Data;

#nullable disable

namespace Projet6_ModelisezEtcreezUneBaseDeDonnee.Migrations
{
    [DbContext(typeof(NexaWorksContext))]
    partial class NexaWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OsModeleVersionModele", b =>
                {
                    b.Property<int>("SupportedOsOsId")
                        .HasColumnType("int");

                    b.Property<int>("SupportedVersionsVersionId")
                        .HasColumnType("int");

                    b.HasKey("SupportedOsOsId", "SupportedVersionsVersionId");

                    b.HasIndex("SupportedVersionsVersionId");

                    b.ToTable("VersionOsSupport", (string)null);

                    b.HasData(
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 1
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 1
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 2
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 2
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 2
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 3
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 3
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 3
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 3
                        },
                        new
                        {
                            SupportedOsOsId = 5,
                            SupportedVersionsVersionId = 3
                        },
                        new
                        {
                            SupportedOsOsId = 6,
                            SupportedVersionsVersionId = 3
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 4
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 4
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 4
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 4
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 5
                        },
                        new
                        {
                            SupportedOsOsId = 5,
                            SupportedVersionsVersionId = 5
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 6
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 6
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 6
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 7
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 7
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 7
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 7
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 8
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 8
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 9
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 9
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 9
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 9
                        },
                        new
                        {
                            SupportedOsOsId = 5,
                            SupportedVersionsVersionId = 9
                        },
                        new
                        {
                            SupportedOsOsId = 6,
                            SupportedVersionsVersionId = 9
                        },
                        new
                        {
                            SupportedOsOsId = 1,
                            SupportedVersionsVersionId = 10
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 10
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 10
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 10
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 11
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 11
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 11
                        },
                        new
                        {
                            SupportedOsOsId = 5,
                            SupportedVersionsVersionId = 11
                        },
                        new
                        {
                            SupportedOsOsId = 3,
                            SupportedVersionsVersionId = 12
                        },
                        new
                        {
                            SupportedOsOsId = 2,
                            SupportedVersionsVersionId = 12
                        },
                        new
                        {
                            SupportedOsOsId = 4,
                            SupportedVersionsVersionId = 12
                        },
                        new
                        {
                            SupportedOsOsId = 5,
                            SupportedVersionsVersionId = 12
                        });
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.OsModele", b =>
                {
                    b.Property<int>("OsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OsId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OsId");

                    b.ToTable("Os");

                    b.HasData(
                        new
                        {
                            OsId = 1,
                            Description = "Système d'exploitation open source basé sur le noyau Linux",
                            OsName = "Linux"
                        },
                        new
                        {
                            OsId = 2,
                            Description = "Système d'exploitation Microsoft Windows",
                            OsName = "Windows"
                        },
                        new
                        {
                            OsId = 3,
                            Description = "Système d'exploitation Apple pour ordinateurs Mac",
                            OsName = "MacOS"
                        },
                        new
                        {
                            OsId = 4,
                            Description = "Système d'exploitation mobile basé sur Linux",
                            OsName = "Android"
                        },
                        new
                        {
                            OsId = 5,
                            Description = "Système d'exploitation mobile Apple",
                            OsName = "iOS"
                        },
                        new
                        {
                            OsId = 6,
                            Description = "Système d'exploitation mobile Microsoft",
                            OsName = "WindowsMobile"
                        });
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.ProductModele", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Application de trading pour débutants avec fonctionnalités d'apprentissage",
                            ProductName = "Trader en Herbe"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Application de trading avancée avec outils d'analyse professionnels",
                            ProductName = "Maître des Investissements"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Application de planification et suivi d'activités sportives",
                            ProductName = "Planificateur d'Entraînement"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Application d'aide à la gestion de l'anxiété et du stress social",
                            ProductName = "Planificateur d'Anxiété Sociale"
                        });
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.TicketModele", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OsId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("IX_Ticket_DateCreation");

                    b.HasIndex("OsId")
                        .HasDatabaseName("IX_Ticket_OsId");

                    b.HasIndex("Statut")
                        .HasDatabaseName("IX_Ticket_Statut");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("IX_Ticket_VersionId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            DateCreation = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L'application se ferme brutalement lors de la tentative d'importation des activités depuis des montres connectées Garmin sur les appareils iOS 17.4 et supérieurs. Les utilisateurs ne peuvent pas intégrer leurs données d'entraînement existantes.",
                            OsId = 5,
                            Resolution = "Actuellement en investigation. L'analyse préliminaire suggère un conflit avec la nouvelle politique de sécurité iOS concernant les connexions Bluetooth. L'équipe travaille sur une solution qui maintient la compatibilité tout en respectant les nouvelles restrictions d'Apple.",
                            Statut = "En cours",
                            VersionId = 9
                        },
                        new
                        {
                            TicketId = 2,
                            DateCreation = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les rappels d'entraînement programmés ne déclenchent pas de vibration sur les appareils Windows Mobile, uniquement une notification visuelle facilement manquée.",
                            OsId = 6,
                            Resolution = "Correction de l'implémentation des notifications pour utiliser correctement l'API de vibration de Windows Mobile. Ajout d'un paramètre permettant à l'utilisateur de personnaliser l'intensité et la durée des vibrations. Implémentation d'un mode \"ne pas déranger\" configurable par plages horaires.",
                            Statut = "Résolu",
                            VersionId = 9
                        },
                        new
                        {
                            TicketId = 3,
                            DateCreation = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fuite de mémoire critique identifiée lors de l'utilisation prolongée. L'application peut consommer jusqu'à 8 Go de RAM après quelques heures d'utilisation, ralentissant considérablement le système.",
                            OsId = 3,
                            Resolution = "Analyse en cours avec des outils de profilage mémoire. Plusieurs sources potentielles identifiées dans le gestionnaire de modèles 3D pour la visualisation des exercices. Un correctif temporaire est en développement pour libérer périodiquement la mémoire, tandis qu'une solution permanente nécessite une refonte plus importante de l'architecture.",
                            Statut = "En cours",
                            VersionId = 10
                        },
                        new
                        {
                            TicketId = 4,
                            DateCreation = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Incompatibilité avec les pilotes graphiques NVIDIA récents (série 550 et supérieure). Artefacts visuels et flickering lors de l'affichage des modèles d'exercices en 3D.",
                            OsId = 2,
                            Resolution = "Mise à jour du moteur de rendu 3D pour contourner un bug dans les pilotes NVIDIA. Implémentation d'une solution de repli utilisant DirectX 11 au lieu de DirectX 12 lorsque des problèmes sont détectés. Collaboration avec l'équipe NVIDIA pour résoudre le problème de manière permanente dans les futures mises à jour des pilotes.",
                            Statut = "Résolu",
                            VersionId = 10
                        },
                        new
                        {
                            TicketId = 5,
                            DateCreation = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Disparition aléatoire des données historiques d'entraînement sur certains appareils Android 13. Les utilisateurs perdent leur historique sans action spécifique de leur part.",
                            OsId = 4,
                            Resolution = "Problème complexe en cours d'investigation. Les tests initiaux suggèrent une interaction problématique entre le système de stockage de l'application et le gestionnaire de stockage scoped d'Android 13. Une solution de contournement temporaire a été mise en place via une sauvegarde cloud automatique, mais la résolution définitive nécessite des modifications architecturales importantes.",
                            Statut = "En cours",
                            VersionId = 10
                        },
                        new
                        {
                            TicketId = 6,
                            DateCreation = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Le suivi GPS des activités en extérieur est inexact sur iOS, avec des écarts de distance pouvant atteindre 30% par rapport aux mesures réelles ou à d'autres applications.",
                            OsId = 5,
                            Resolution = "Refonte complète du module de suivi GPS avec implémentation d'algorithmes de filtrage plus sophistiqués. Optimisation de la fréquence d'échantillonnage pour équilibrer précision et consommation de batterie. Ajout d'une calibration automatique basée sur les habitudes de course de l'utilisateur. Les tests montrent une amélioration de la précision à moins de 3% d'écart.",
                            Statut = "Résolu",
                            VersionId = 10
                        },
                        new
                        {
                            TicketId = 7,
                            DateCreation = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les enregistrements audio des exercices de relaxation sont systématiquement corrompus après installation sur Windows 11. L'audio est saccadé et inintelligible.",
                            OsId = 2,
                            Resolution = "Investigation en cours sur un conflit potentiel avec le nouveau codec audio de Windows 11. Tests en cours avec des formats audio alternatifs et différentes méthodes de lecture. Une version bêta avec solution temporaire est disponible pour les utilisateurs affectés, utilisant un moteur audio tiers au lieu des API système.",
                            Statut = "En cours",
                            VersionId = 11
                        },
                        new
                        {
                            TicketId = 8,
                            DateCreation = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les exercices de méditation guidée sont interrompus par les notifications système malgré l'activation du mode \"Ne pas déranger\" dans l'application.",
                            OsId = 4,
                            Resolution = "Implémentation d'une intégration directe avec l'API \"Ne pas déranger\" d'Android pour activer automatiquement le mode système lors des sessions. Ajout d'options de personnalisation permettant de filtrer certaines notifications prioritaires. Optimisation de la reprise des exercices en cas d'interruption inévitable.",
                            Statut = "Résolu",
                            VersionId = 11
                        },
                        new
                        {
                            TicketId = 9,
                            DateCreation = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vulnérabilité de sécurité critique : les journaux personnels des utilisateurs sont stockés en texte clair et accessibles sans authentification si l'on accède physiquement à l'appareil.",
                            OsId = 3,
                            Resolution = "En cours de correction prioritaire. Développement d'un système de chiffrement transparent des données sensibles avec authentification biométrique ou par mot de passe. Migration des données existantes vers le nouveau format sécurisé. Un audit de sécurité externe a été commandé pour valider la solution avant déploiement.",
                            Statut = "En cours",
                            VersionId = 12
                        },
                        new
                        {
                            TicketId = 10,
                            DateCreation = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les rappels pour les exercices programmés n'apparaissent pas dans le Centre de notifications Windows, rendant l'application moins efficace pour la formation aux habitudes quotidiennes.",
                            OsId = 2,
                            Resolution = "Refonte complète du système de notification pour utiliser l'API Windows Toast moderne au lieu de l'ancien système. Ajout d'options de personnalisation avancées pour l'apparence et le comportement des notifications. Implémentation d'un système de rappels progressifs dont l'insistance augmente si les exercices sont régulièrement ignorés.",
                            Statut = "Résolu",
                            VersionId = 12
                        },
                        new
                        {
                            TicketId = 11,
                            DateCreation = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Problème de sécurité : les mots de passe sont stockés en clair dans un fichier de configuration accessible. Risque de compromission des comptes utilisateurs.",
                            OsId = 1,
                            Resolution = "Analyse en cours. Solution planifiée pour implémenter un stockage sécurisé avec chiffrement AES-256. Mise en place d'un mécanisme de migration automatique des identifiants existants vers le nouveau système sécurisé. La correction est en phase finale de tests et sera déployée après l'audit de sécurité externe.",
                            Statut = "En cours",
                            VersionId = 1
                        },
                        new
                        {
                            TicketId = 12,
                            DateCreation = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dégradation progressive des performances sur iPad : l'application devient de plus en plus lente à chaque session jusqu'à devenir inutilisable, nécessitant une réinstallation.",
                            OsId = 5,
                            Resolution = "Correction d'un problème dans le système de cache qui accumulait des données sans jamais les purger. Implémentation d'un mécanisme intelligent de gestion de cache avec limite de taille configurable et nettoyage automatique lors de la fermeture de l'application. Ajout d'une option dans les paramètres permettant à l'utilisateur de vider manuellement le cache.",
                            Statut = "Résolu",
                            VersionId = 5
                        },
                        new
                        {
                            TicketId = 13,
                            DateCreation = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les utilisateurs signalent l'apparition de publicités intrusives malgré l'achat de la version premium sans publicité. Les annonces apparaissent aléatoirement pendant les exercices de méditation.",
                            OsId = 5,
                            Resolution = "Problème prioritaire en cours d'investigation. L'analyse préliminaire suggère un conflit avec la dernière mise à jour du framework publicitaire tiers. Une solution temporaire consiste à désactiver complètement le module publicitaire en attendant une correction permanente. L'équipe développe actuellement un correctif d'urgence qui sera déployé d'ici 7 jours.",
                            Statut = "En cours",
                            VersionId = 12
                        },
                        new
                        {
                            TicketId = 14,
                            DateCreation = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Arrêts inattendus de l'application lors de l'ouverture simultanée de plus de trois graphiques de tendance. Message d'erreur indiquant \"Ressources insuffisantes\".",
                            OsId = 2,
                            Resolution = "Optimisation majeure de la gestion des ressources graphiques avec mise en place d'un système de mise en cache intelligente. Implémentation d'un mécanisme de rendu adaptatif qui ajuste automatiquement la qualité et la fréquence de rafraîchissement des graphiques en fonction des capacités matérielles détectées. Amélioration de 70% de l'utilisation mémoire et réduction de 60% de l'utilisation CPU.",
                            Statut = "Résolu",
                            VersionId = 3
                        },
                        new
                        {
                            TicketId = 15,
                            DateCreation = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Synchronisation défectueuse entre appareils : les modifications du portefeuille effectuées sur Android ne sont pas reflétées sur les autres plateformes (iOS, Web) malgré une connexion internet stable.",
                            OsId = 4,
                            Resolution = "Investigation en cours. Les journaux serveur montrent des incohérences dans les jetons d'authentification entre plateformes, entraînant des rejets de synchronisation. L'équipe backend travaille sur une refonte du système de synchronisation multi-appareils avec un nouveau protocole de validation et résolution de conflits. Une version test est en cours de déploiement pour validation interne.",
                            Statut = "En cours",
                            VersionId = 7
                        },
                        new
                        {
                            TicketId = 16,
                            DateCreation = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Échec du démarrage de l'application sur les distributions Linux basées sur Fedora 39. L'application affiche un message d'erreur concernant des bibliothèques Qt incompatibles avant de se fermer.",
                            OsId = 1,
                            Resolution = "Investigation en cours. Tests préliminaires indiquent une incompatibilité avec la nouvelle version de la bibliothèque Qt 6.6 incluse dans Fedora 39. L'équipe travaille sur deux approches parallèles : une solution de compatibilité pour Qt 6.6 et un package contenant toutes les dépendances nécessaires en version compatible, à distribuer avec l'application.",
                            Statut = "En cours",
                            VersionId = 2
                        },
                        new
                        {
                            TicketId = 17,
                            DateCreation = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Les utilisateurs de MacBook Pro M2 signalent une surchauffe excessive lors de l'utilisation intensive de l'application. La température du CPU peut atteindre 95°C, déclenchant les ventilateurs à pleine vitesse et réduisant l'autonomie de la batterie.",
                            OsId = 3,
                            Resolution = "Optimisation majeure du code de rendu graphique pour les architectures ARM. Implémentation d'un mécanisme de limitation de fréquence d'images adaptatif qui réduit la charge CPU lorsque l'application n'est pas en premier plan ou lors d'une inactivité utilisateur. Ajout d'un mode économie d'énergie optionnel qui privilégie l'autonomie à la fluidité des animations. Tests montrent une réduction de 40% de la consommation CPU et une diminution de température moyenne de 15°C.",
                            Statut = "Résolu",
                            VersionId = 3
                        },
                        new
                        {
                            TicketId = 18,
                            DateCreation = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Faille de sécurité critique identifiée : l'intégration avec le navigateur web stocke temporairement les données des transactions dans un fichier non chiffré accessible par d'autres applications. Risque d'extraction de données sensibles par des logiciels malveillants.",
                            OsId = 2,
                            Resolution = "Équipe de sécurité mobilisée en priorité. Développement d'un correctif d'urgence qui implémente un stockage temporaire en mémoire encryptée au lieu d'utiliser le système de fichiers. Audit de sécurité complet en cours sur toutes les fonctionnalités impliquant des données sensibles. Publication d'un avertissement de sécurité et recommandations temporaires aux utilisateurs en attendant le déploiement de la mise à jour.",
                            Statut = "En cours",
                            VersionId = 4
                        },
                        new
                        {
                            TicketId = 19,
                            DateCreation = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Support incomplet des fonctionnalités d'accessibilité MacOS. Les utilisateurs de VoiceOver ne peuvent pas naviguer efficacement dans l'interface ou accéder à certaines fonctionnalités essentielles comme la configuration des alertes de prix.",
                            OsId = 3,
                            Resolution = "Refonte complète de l'interface utilisateur avec implémentation des contrôles d'accessibilité d'Apple. Ajout de descriptions détaillées pour tous les éléments d'interface et de raccourcis clavier alternatifs pour les actions principales. Optimisation des flux de navigation pour VoiceOver. Tests d'accessibilité réalisés avec des utilisateurs malvoyants pour valider les améliorations. Mise en place d'un processus de validation d'accessibilité pour toutes les futures fonctionnalités.",
                            Statut = "Résolu",
                            VersionId = 5
                        },
                        new
                        {
                            TicketId = 20,
                            DateCreation = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "La fonctionnalité de capture d'écran et partage sur réseaux sociaux échoue sur Android 14. L'application affiche une erreur \"Accès refusé\" malgré les autorisations accordées.",
                            OsId = 4,
                            Resolution = "Adaptation de la fonctionnalité de capture et partage aux nouvelles restrictions de sécurité d'Android 14 concernant l'accès au contenu de l'écran. Mise à jour de la méthode de demande d'autorisation avec utilisation du nouveau framework de permissions granulaires. Ajout d'un mode de partage alternatif qui génère une image à partir des données internes plutôt que de capturer l'écran. Amélioration des messages d'erreur avec instructions spécifiques pour chaque version d'Android.",
                            Statut = "Résolu",
                            VersionId = 6
                        },
                        new
                        {
                            TicketId = 21,
                            DateCreation = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multiples erreurs d'affichage sur les configurations multi-écrans. Les fenêtres flottantes d'analyse apparaissent au mauvais endroit ou sont partiellement visibles lorsqu'elles sont déplacées entre écrans avec des résolutions différentes.",
                            OsId = 2,
                            Resolution = "Investigation en cours sur les problèmes de gestion de fenêtres dans des configurations d'affichage complexes. Tests réalisés avec diverses combinaisons de résolutions et échelles DPI. Solution envisagée implique une refonte du système de positionnement des fenêtres avec détection et ajustement automatique aux caractéristiques de chaque écran. Développement d'un mode de test permettant de simuler diverses configurations d'affichage.",
                            Statut = "En cours",
                            VersionId = 7
                        },
                        new
                        {
                            TicketId = 22,
                            DateCreation = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "L'application n'utilise pas les thèmes système sous GNOME et KDE, générant un contraste insuffisant en mode sombre et des problèmes de lisibilité des graphiques d'évolution des performances.",
                            OsId = 1,
                            Resolution = "Implémentation de la détection automatique du thème système sur les environnements de bureau Linux. Adaptation dynamique des palettes de couleurs pour maintenir un contraste optimal quel que soit le thème. Refonte des graphiques avec des couleurs adaptatives qui s'ajustent automatiquement aux préférences d'affichage de l'utilisateur. Ajout de préréglages de couleurs alternatifs pour les utilisateurs daltoniennes ou ayant des besoins visuels spécifiques.",
                            Statut = "Résolu",
                            VersionId = 8
                        },
                        new
                        {
                            TicketId = 23,
                            DateCreation = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Consommation excessive de batterie en raison de l'utilisation continue du GPS même lorsque l'utilisateur n'est pas en activité. Certains utilisateurs rapportent jusqu'à 40% de batterie consommée en une journée par l'application en arrière-plan.",
                            OsId = 4,
                            Resolution = "Analyse approfondie en cours du cycle de vie de l'application et de la gestion des capteurs. Développement d'un système intelligent de détection d'activité qui n'active le GPS que lorsque nécessaire. Implémentation d'un algorithme de prédiction qui anticipe les périodes d'entraînement basées sur les habitudes de l'utilisateur. Tests en cours avec diverses intensités d'utilisation pour mesurer l'impact des optimisations. Première version bêta du correctif disponible pour les testeurs volontaires.",
                            Statut = "En cours",
                            VersionId = 9
                        },
                        new
                        {
                            TicketId = 24,
                            DateCreation = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateResolution = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Échec des enregistrements audio dans le journal des émotions sur les appareils Samsung utilisant One UI 6. L'application se fige pendant plusieurs secondes avant d'afficher une erreur \"Périphérique audio non disponible\".",
                            OsId = 4,
                            Resolution = "Correction d'un problème d'incompatibilité avec l'API d'enregistrement audio modifiée dans One UI 6. Implémentation d'une détection automatique de la version de l'interface Samsung et utilisation de l'API appropriée selon le système. Ajout d'un mécanisme de secours qui bascule sur une méthode d'enregistrement alternative en cas d'échec de la méthode principale. Amélioration des messages d'erreur avec suggestions de résolution spécifiques pour chaque modèle d'appareil.",
                            Statut = "Résolu",
                            VersionId = 11
                        },
                        new
                        {
                            TicketId = 25,
                            DateCreation = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Disparition des données après restauration de l'appareil ou transfert vers un nouvel iPhone. La sauvegarde iCloud ne semble pas préserver correctement les journaux personnels et les statistiques d'évolution.",
                            OsId = 5,
                            Resolution = "Investigation en cours sur l'implémentation de CloudKit. Identification préliminaire d'erreurs dans la structure des données stockées qui empêchent la restauration correcte. Développement d'un utilitaire de récupération qui peut extraire les données des sauvegardes iCloud même en cas de structure incompatible. Refonte du système de stockage cloud avec validation plus stricte des données avant synchronisation et mécanismes de récupération robustes. Beta planifiée pour la semaine prochaine avec les utilisateurs affectés.",
                            Statut = "En cours",
                            VersionId = 12
                        });
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.VersionModele", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VersionId");

                    b.HasIndex("ProductId", "VersionName")
                        .IsUnique()
                        .HasDatabaseName("IX_Version_ProductId_VersionName");

                    b.ToTable("Versions");

                    b.HasData(
                        new
                        {
                            VersionId = 1,
                            Description = "Version initiale - Trader en Herbe",
                            ProductId = 1,
                            VersionName = "1.0"
                        },
                        new
                        {
                            VersionId = 2,
                            Description = "Première mise à jour - Trader en Herbe",
                            ProductId = 1,
                            VersionName = "1.1"
                        },
                        new
                        {
                            VersionId = 3,
                            Description = "Deuxième mise à jour - Trader en Herbe",
                            ProductId = 1,
                            VersionName = "1.2"
                        },
                        new
                        {
                            VersionId = 4,
                            Description = "Troisième mise à jour - Trader en Herbe",
                            ProductId = 1,
                            VersionName = "1.3"
                        },
                        new
                        {
                            VersionId = 5,
                            Description = "Version initiale - Maître des Investissements",
                            ProductId = 2,
                            VersionName = "1.0"
                        },
                        new
                        {
                            VersionId = 6,
                            Description = "Version majeure 2.0 - Maître des Investissements",
                            ProductId = 2,
                            VersionName = "2.0"
                        },
                        new
                        {
                            VersionId = 7,
                            Description = "Mise à jour 2.1 - Maître des Investissements",
                            ProductId = 2,
                            VersionName = "2.1"
                        },
                        new
                        {
                            VersionId = 8,
                            Description = "Version initiale - Planificateur d'Entraînement",
                            ProductId = 3,
                            VersionName = "1.0"
                        },
                        new
                        {
                            VersionId = 9,
                            Description = "Première mise à jour - Planificateur d'Entraînement",
                            ProductId = 3,
                            VersionName = "1.1"
                        },
                        new
                        {
                            VersionId = 10,
                            Description = "Version majeure 2.0 - Planificateur d'Entraînement",
                            ProductId = 3,
                            VersionName = "2.0"
                        },
                        new
                        {
                            VersionId = 11,
                            Description = "Version initiale - Planificateur d'Anxiété Sociale",
                            ProductId = 4,
                            VersionName = "1.0"
                        },
                        new
                        {
                            VersionId = 12,
                            Description = "Première mise à jour - Planificateur d'Anxiété Sociale",
                            ProductId = 4,
                            VersionName = "1.1"
                        });
                });

            modelBuilder.Entity("OsModeleVersionModele", b =>
                {
                    b.HasOne("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.OsModele", null)
                        .WithMany()
                        .HasForeignKey("SupportedOsOsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.VersionModele", null)
                        .WithMany()
                        .HasForeignKey("SupportedVersionsVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.TicketModele", b =>
                {
                    b.HasOne("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.OsModele", "Os")
                        .WithMany("Tickets")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.VersionModele", "Version")
                        .WithMany("Tickets")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Os");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.VersionModele", b =>
                {
                    b.HasOne("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.ProductModele", "Product")
                        .WithMany("Versions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.OsModele", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.ProductModele", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Projet6_ModelisezEtcreezUneBaseDeDonnee.Models.VersionModele", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
